# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from clients.python.src.main.proto import minecraft_pb2 as src_dot_main_dot_proto_dot_minecraft__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/main/proto/minecraft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MinecraftServiceStub(object):
    """*
    The main service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.spawnBlocks = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/spawnBlocks',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.readEntities = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/readEntities',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Uuids.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Entities.FromString,
                _registered_method=True)
        self.spawnEntities = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/spawnEntities',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.SpawnEntities.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Uuids.FromString,
                _registered_method=True)
        self.readCube = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/readCube',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.FromString,
                _registered_method=True)
        self.fillCube = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/fillCube',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.FillCubeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.readEntitiesInSphere = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/readEntitiesInSphere',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Sphere.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Entities.FromString,
                _registered_method=True)
        self.getBiomeAt = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/getBiomeAt',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.BiomeResponse.FromString,
                _registered_method=True)
        self.setLoc = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/setLoc',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
                _registered_method=True)
        self.setRot = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/setRot',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.setPlayerLocRot = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/setPlayerLocRot',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.LocRotMsg.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.initDataGen = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/initDataGen',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getHighestYAt = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/getHighestYAt',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
                _registered_method=True)
        self.setLocY = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/setLocY',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
                _registered_method=True)
        self.readCubeAndBiome = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/readCubeAndBiome',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.FromString,
                _registered_method=True)
        self.readCubeAndBiomeMetadata = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/readCubeAndBiomeMetadata',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.FromString,
                _registered_method=True)
        self.readDenseCubeWithMetadata = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/readDenseCubeWithMetadata',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.DenseCube.FromString,
                _registered_method=True)
        self.readDenseCubeWithMajority = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/readDenseCubeWithMajority',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.DenseCubeMajority.FromString,
                _registered_method=True)
        self.setModelArea = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/setModelArea',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.SetAreaRequest.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
                _registered_method=True)
        self.getCurrentBuildingArea = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/getCurrentBuildingArea',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.BuildingArea.FromString,
                _registered_method=True)
        self.triggerModel = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/triggerModel',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
                _registered_method=True)
        self.HandleLoadPreset = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/HandleLoadPreset',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.LoadPresetRequest.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
                _registered_method=True)
        self.ModifyTerrain = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/ModifyTerrain',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.TerrainModificationRequest.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
                _registered_method=True)
        self.Terraform = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/Terraform',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.TerraformRequest.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
                _registered_method=True)
        self.setActiveDimension = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/setActiveDimension',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.DimensionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.preloadChunks = channel.unary_unary(
                '/dk.itu.real.ooe.MinecraftService/preloadChunks',
                request_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.PreloadChunksRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class MinecraftServiceServicer(object):
    """*
    The main service.
    """

    def spawnBlocks(self, request, context):
        """* Spawn multiple blocks. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readEntities(self, request, context):
        """* Reads multiple entities *
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def spawnEntities(self, request, context):
        """* Spawn multiple entities. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readCube(self, request, context):
        """* Return all blocks in a cube 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def fillCube(self, request, context):
        """* Fill a cube with a block type 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readEntitiesInSphere(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBiomeAt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setLoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setRot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setPlayerLocRot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def initDataGen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getHighestYAt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setLocY(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readCubeAndBiome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readCubeAndBiomeMetadata(self, request, context):
        """* Return all blocks in a cube, including per-block metadata 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readDenseCubeWithMetadata(self, request, context):
        """* Return dense arrays for blocks + biome ids, plus sparse metadata for relevant blocks 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readDenseCubeWithMajority(self, request, context):
        """* Return dense arrays for blocks + a single majority-biome label for the whole cube 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setModelArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCurrentBuildingArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def triggerModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleLoadPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyTerrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terraform(self, request, context):
        """Trigger diffusion-based terrain generation and spawning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setActiveDimension(self, request, context):
        """Switch active dimension/world for subsequent RPC operations; optionally teleport player
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def preloadChunks(self, request, context):
        """Force-load/generate chunks in the active dimension within a block-area
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MinecraftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'spawnBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.spawnBlocks,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'readEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.readEntities,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Uuids.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Entities.SerializeToString,
            ),
            'spawnEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.spawnEntities,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.SpawnEntities.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Uuids.SerializeToString,
            ),
            'readCube': grpc.unary_unary_rpc_method_handler(
                    servicer.readCube,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.SerializeToString,
            ),
            'fillCube': grpc.unary_unary_rpc_method_handler(
                    servicer.fillCube,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.FillCubeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'readEntitiesInSphere': grpc.unary_unary_rpc_method_handler(
                    servicer.readEntitiesInSphere,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Sphere.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Entities.SerializeToString,
            ),
            'getBiomeAt': grpc.unary_unary_rpc_method_handler(
                    servicer.getBiomeAt,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.BiomeResponse.SerializeToString,
            ),
            'setLoc': grpc.unary_unary_rpc_method_handler(
                    servicer.setLoc,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
            ),
            'setRot': grpc.unary_unary_rpc_method_handler(
                    servicer.setRot,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'setPlayerLocRot': grpc.unary_unary_rpc_method_handler(
                    servicer.setPlayerLocRot,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.LocRotMsg.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'initDataGen': grpc.unary_unary_rpc_method_handler(
                    servicer.initDataGen,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getHighestYAt': grpc.unary_unary_rpc_method_handler(
                    servicer.getHighestYAt,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
            ),
            'setLocY': grpc.unary_unary_rpc_method_handler(
                    servicer.setLocY,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
            ),
            'readCubeAndBiome': grpc.unary_unary_rpc_method_handler(
                    servicer.readCubeAndBiome,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.SerializeToString,
            ),
            'readCubeAndBiomeMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.readCubeAndBiomeMetadata,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.SerializeToString,
            ),
            'readDenseCubeWithMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.readDenseCubeWithMetadata,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.DenseCube.SerializeToString,
            ),
            'readDenseCubeWithMajority': grpc.unary_unary_rpc_method_handler(
                    servicer.readDenseCubeWithMajority,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.Cube.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.DenseCubeMajority.SerializeToString,
            ),
            'setModelArea': grpc.unary_unary_rpc_method_handler(
                    servicer.setModelArea,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.SetAreaRequest.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.SerializeToString,
            ),
            'getCurrentBuildingArea': grpc.unary_unary_rpc_method_handler(
                    servicer.getCurrentBuildingArea,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.BuildingArea.SerializeToString,
            ),
            'triggerModel': grpc.unary_unary_rpc_method_handler(
                    servicer.triggerModel,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.SerializeToString,
            ),
            'HandleLoadPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleLoadPreset,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.LoadPresetRequest.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.SerializeToString,
            ),
            'ModifyTerrain': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyTerrain,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.TerrainModificationRequest.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.SerializeToString,
            ),
            'Terraform': grpc.unary_unary_rpc_method_handler(
                    servicer.Terraform,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.TerraformRequest.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.SerializeToString,
            ),
            'setActiveDimension': grpc.unary_unary_rpc_method_handler(
                    servicer.setActiveDimension,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.DimensionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'preloadChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.preloadChunks,
                    request_deserializer=src_dot_main_dot_proto_dot_minecraft__pb2.PreloadChunksRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dk.itu.real.ooe.MinecraftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dk.itu.real.ooe.MinecraftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MinecraftService(object):
    """*
    The main service.
    """

    @staticmethod
    def spawnBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/spawnBlocks',
            src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/readEntities',
            src_dot_main_dot_proto_dot_minecraft__pb2.Uuids.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.Entities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def spawnEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/spawnEntities',
            src_dot_main_dot_proto_dot_minecraft__pb2.SpawnEntities.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.Uuids.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readCube(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/readCube',
            src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def fillCube(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/fillCube',
            src_dot_main_dot_proto_dot_minecraft__pb2.FillCubeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readEntitiesInSphere(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/readEntitiesInSphere',
            src_dot_main_dot_proto_dot_minecraft__pb2.Sphere.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.Entities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getBiomeAt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/getBiomeAt',
            src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.BiomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setLoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/setLoc',
            src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setRot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/setRot',
            src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setPlayerLocRot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/setPlayerLocRot',
            src_dot_main_dot_proto_dot_minecraft__pb2.LocRotMsg.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def initDataGen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/initDataGen',
            src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getHighestYAt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/getHighestYAt',
            src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setLocY(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/setLocY',
            src_dot_main_dot_proto_dot_minecraft__pb2.Point.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.Point.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readCubeAndBiome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/readCubeAndBiome',
            src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readCubeAndBiomeMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/readCubeAndBiomeMetadata',
            src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.Blocks.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readDenseCubeWithMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/readDenseCubeWithMetadata',
            src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.DenseCube.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readDenseCubeWithMajority(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/readDenseCubeWithMajority',
            src_dot_main_dot_proto_dot_minecraft__pb2.Cube.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.DenseCubeMajority.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setModelArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/setModelArea',
            src_dot_main_dot_proto_dot_minecraft__pb2.SetAreaRequest.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCurrentBuildingArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/getCurrentBuildingArea',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.BuildingArea.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def triggerModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/triggerModel',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleLoadPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/HandleLoadPreset',
            src_dot_main_dot_proto_dot_minecraft__pb2.LoadPresetRequest.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyTerrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/ModifyTerrain',
            src_dot_main_dot_proto_dot_minecraft__pb2.TerrainModificationRequest.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Terraform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/Terraform',
            src_dot_main_dot_proto_dot_minecraft__pb2.TerraformRequest.SerializeToString,
            src_dot_main_dot_proto_dot_minecraft__pb2.TriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setActiveDimension(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/setActiveDimension',
            src_dot_main_dot_proto_dot_minecraft__pb2.DimensionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def preloadChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dk.itu.real.ooe.MinecraftService/preloadChunks',
            src_dot_main_dot_proto_dot_minecraft__pb2.PreloadChunksRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
